version: "3.9"
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
    - "5432:5432"
    env_file:
    - ./.env
    volumes:
    - data:/var/lib/postgresql/data
    networks:
    - backend
    restart: always
  backend:
    container_name: backend
    build: ./backend
    image: backend
    env_file:
    - ./.env
    ports: 
    - "8081:3000"
    depends_on: 
    - postgres
    networks:
    - backend
    restart: always
  frontend:
    container_name: frontend
    build: ./frontend
    image: frontend
    ports: 
    - "4000:80"
    depends_on: 
    - backend
    restart: always

volumes:
  data:

networks:
  backend: