version: "3.9"
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - backend
  backend:
     container_name: backend
     build: ./backend
     image: backend
     env_file:
      - ./.env
     ports: 
     - "8081:3000"
     depends_on: 
     - postgres
     networks:
     - backend
  frontend:
    container_name: frontend
    build: ./frontend
    image: frontend
    ports: 
    - "4000:80"
    restart: always
    depends_on: 
     - backend

volumes:
 data:

networks:
  backend: